# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
    packages:
      - libglu1-mesa-dev 
      - freeglut3-dev 
      - mesa-common-dev
      
r_binary_packages:
  - rgl

before_cache:
  - Rscript -e 'install.packages("remotes")'
  - Rscript -e 'remotes::install_cran(c("rmarkdown", "assertthat", "covr", "testthat", "purrr", "magrittr", "dplyr", "readr", "zoo", "png"))'

cache:
  packages: true
  directories:
    - /usr/local/lib/R/site-library
    - /usr/lib/R

services:
  - xvfb

after_success:
    - Rscript -e 'covr::codecov()'
    
after_failure:
  - if [ -f /home/travis/build/heike/x3ptools/x3ptools.Rcheck/00install.out ]; then cat /home/travis/build/heike/x3ptools/x3ptools.Rcheck/00install.out; fi