# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_packages:
  - covr

r_binary_packages:
  - rgl

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
    packages:
      - libmagick++-dev

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

after_success:
    - Rscript -e 'covr::codecov()'
    
after_failure:
  - if [ -f /home/travis/build/heike/x3ptools/x3ptools.Rcheck/00install.out ]; then cat /home/travis/build/heike/x3ptools/x3ptools.Rcheck/00install.out; fi